tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_cs_fixer:
            config: { level: psr2 } # or psr1 if you would just like to get fixes for PSR1
    php_code_sniffer:
            config:
                standard: "PSR2"

filter:
    excluded_paths:
        - 'tests/*'
        - 'features/*'
        - 'fixtures/*'

build:
  project_setup:
    before:
      -
        command: 'phantomjs --webdriver=8643'
        background: true
      # run migrations
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local
      - wget http://samsoncms.local

  dependencies:
    before:
       - mysql -uroot -e 'CREATE DATABASE samsoncms'
       - mysql -uroot -e "CREATE USER 'samsoncms'@'localhost' IDENTIFIED BY 'AzUzrcVe4LJJre9f'";
       - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'samsoncms'@'localhost' WITH GRANT OPTION";

  environment:
    php:
      version: 5.5
    variables:
        APPLICATION_ENV: scrutinizer
    hosts:
      samsoncms.local: '127.0.0.1'
    apache2:
      modules: ['rewrite']
      sites:
        samsoncms:
          web_root: 'www/'
          host: 'samsoncms.local'

  tests:
    ovveride:
      - 'vendor/bin/behat -p scrutinizer'

