language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
  - sudo sed -i -e "/DocumentRoot/i\ServerName test.local" /etc/apache2/sites-available/default
  - echo "127.0.0.1 test.local" | sudo tee -a /etc/hosts
  - sudo /etc/init.d/apache2 restart

script:
 - vendor/bin/behat -c phantomjs