language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_cache:
  - sudo rm -f vendor/samson*

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7

env:
  global:
    - APPLICATION_ENV=travis

matrix:
  allow_failures:
  - php: hhvm
  - php: 7

addons:
  hosts:
    - samsoncms.local

mysql:
  database: samsoncms
  username: root
  encoding: utf8

before_script:
  - sudo apt-get update

  # install apache
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo a2enmod rewrite actions fastcgi alias
  - ls

  # configure webserver
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then sudo ci/travis-apache.sh; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = 'hhvm' ]; then sudo ci/travis-hhvm.sh; fi"

  # rewrite path to www root folder
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default

  # set application environment variable
  - sudo sed -e "s?%APPLICATION_ENV%?$APPLICATION_ENV?g" --in-place /etc/apache2/sites-available/default
  - sudo cat /etc/apache2/sites-available/default

  # restart apache
  - sudo service apache2 restart

  # import base SQL data
  - mysql -e 'create database samsoncms;'
  #- mysql ${DB_NAME} < tests/sql/init.sql

  # Start phantomjs
  - phantomjs --webdriver=8643 &

  # install dependencies
  - travis_retry composer install --prefer-source --no-interaction
  # run migrations
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local
  - wget http://samsoncms.local


script:
#- bin/phpunit --coverage-clover=coverage.clover --coverage-text
 - vendor/bin/behat -p travis

after_script:
 # send result to scrutinizer
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover