language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7

matrix:
  allow_failures:
  - php: hhvm
  - php: 7

addons:
  hosts:
    - samsoncms.local

mysql:
  database: samsoncms
  username: root
  encoding: utf8

before_script:
  - sh ./ci/install-apache.sh

  # Start phantomjs, do we need it?
  - phantomjs --webdriver=8643 &

  # install dependencies
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script:
#- bin/phpunit --coverage-clover=coverage.clover --coverage-text
 - vendor/bin/behat -p travis

after_script:
 # send result to scrutinizer
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover coverage.clover